### ISSUE TITLE
Add a mention in the website that says it is an open source project

### ISSUE THREAD

**Issue by LongJohn-Silver** [openingtree/openingtree#187]
I found your project on AlternativeTo and when I visited it and was trying to find if it was really a libre website or not (since a lot of times things that are listed there are wrong of changed their license) and I had to go to GitHub and search it by name to find it. I think a footer with a github logo or something like that saying that it is open source project would be okay, also on the feedback pop up you could link to the repo.

**Comment by vjuneja** [comment]
https://github.com/openingtree/openingtree/commit/8343a67c9359dfaf7716e62ab97bfb3cd173618d
