### ISSUE TITLE
Support dark mode

### ISSUE THREAD

**Issue by vjuneja** [openingtree/openingtree#192]
There have been multiple requests at this point.

**Comment by piotryordanov** [comment]
I'd be happy to help support theming of that app.
Could you point out at which files I would want to focus to do that?

Also, do you follow any code styles that you want contributor to respect?

**Comment by vjuneja** [comment]
@piotryordanov 
This is already in PR. check above https://github.com/openingtree/openingtree/pull/240

You can look at some of the other things if you are interested. Eg, support for more variants.

**Comment by vjuneja** [comment]
https://github.com/openingtree/openingtree/pull/240
