### ISSUE TITLE
Add an FAQ section

### ISSUE THREAD

**Issue by vjuneja** [openingtree/openingtree#220]
How to get started?
What do the triangles mean?
What is transposition warning?
Bug with chessboard?

**Comment by rajb245** [comment]
I'll add some things I have questions about you can address in the FAQ when you get around to it:
Does the tree account for transpositions? In software like SCID, a move can look like it will only lead to a few games, but when you click the move, you find yourself back in some mainline by transposition with thousands of games. It would be really nice if the opening tree was built on positions, not on counting statistics in games. So the numbers next to a move wouldn't indicate how many times that move has been played in the current position, but how many times the resulting position was reached in the list of games.

**Comment by vjuneja** [comment]
Hi @rajb245 Thanks for your feedback. In fact earlier, openingtree, unintentionally, used to behave like you are suggesting. But if we show the number of times the resulting positions occurs, it can give an incorrect information about what the opponent actually plays. 

Please see https://github.com/openingtree/openingtree/issues/216 for more information about this.

The way it is now, the numbers show the moves that were played by the players. if you click the move, it will still show games in that resulting position from all the different move order.

**Comment by rajb245** [comment]
@vjuneja understood. Your tool is great for the use case you (and others like IM Rosen) suggest, which is to study the repertoire of a specific player for preparation. For general opening study and analysis, I think seeing the possible lines that weren't played in that position, but that result in other lines in the database by transposition, could be useful. I imagine you could mark such moves with a special icon or something to indicate that though the move wasn't played in the database, it results in positions that do exist in the database. I have been working on something very much like openingtree myself using python, with the old behavior of openingtree. But now I'll just pull and use the older version of your tool before https://github.com/openingtree/openingtree/commit/4db5b68163b2b202407f66936e25446a4e8f2067 !

**Comment by vjuneja** [comment]
Actually, I dont think even the old version is going to give you exactly what you are looking for. It will show the 'right' number only if a move has been played once. If a move has not been played at all, the tool will not show anything, which is probably not the desired behavior for you.

**Comment by vjuneja** [comment]
https://github.com/openingtree/openingtree/pull/226
