### ISSUE TITLE
Highlight common mistakes for the user being analyzed

### ISSUE THREAD

**Issue by 77vjdplu1N2h** [openingtree/openingtree#231]
In analyzing your own games, it would be great if there was some easy way to see the mistakes you're making in the opening.

For example, I've reached https://lichess.org/analysis/standard/rn1qkbnr/pp3ppp/2p1p1b1/4N3/3P4/6N1/PPP2PPP/R1BQKB1R%20b%20KQkq%20-%201%207#13 several times as black and I used to move Ne7, but that's a bit of a mistake (according to the database as well as Stockfish).

But the only way to find this type of move right now is to guess based on the ratio of won to lost games which is not really the best measure for a bad or mediocre player.

More or less:

- It would be great if there was some way to list out the common opening mistakes of a user so they can be reviewed in sequence.
- It would also be great if bad or questionable moves were more prominently highlighted when exploring the opening tree.

There are probably multiple ways to do this, but one would simply be looking at the analysis numbers from Stockfish on any game when it's been analyzed by the cloud Stockfish on lichess. For example:

https://lichess.org/jsSi5PES/white#18

c5 is a significant inaccuracy. These really need to be shown somehow when looking at the tree. Most players on lichess will have a ton of games analyzed so it is hopefully not hard to get Stockfish numbers (especially moves flagged as inaccuracies, mistakes, and blunders by the lichess analysis).

I could also imagine a filter that would show all `select one of (blunder, mistake, inaccuracy)` ordered by # of times a user has done that move.

**Comment by vjuneja** [comment]
Closing this as this is not the direction I want to take with openingtree. The best I think we will be able to do will be to show the engine eval of a position but to do filtering and guiding people through it is really out of scope for this project.
