### ISSUE TITLE
Unable to access Opening Book settings when no results are shown

### ISSUE THREAD

**Issue by justinpchang** [openingtree/openingtree#275]
## To reproduce:

- On a fresh view, click the Opening Book tab.
- Click the wrench symbol and de-select all sources.
- The tab now shows the "No moves found" notice, but the settings wrench icon has disappeared and the user is no longer able to reset settings so the tab is unusable.

## Suggested functionality:

- The wrench should still be present in order for the user to update the Opening Book settings to display other results.

**Comment by jitwit** [comment]
Yes! I experienced the same problem. patch #274 can prevent this from happening

**Comment by vjuneja** [comment]
merged. Thanks @jitwit
