### ISSUE TITLE
Add Save/Load

### ISSUE THREAD

**Issue by Raffa2005** [openingtree/openingtree#290]
A feature that lets you store the created opening tree (also one from custom pgn games) on your machine, to then be able to load it at any time.

**Comment by vjuneja** [comment]
This already exists. You can save the built tree using the save .tree file button after you analyze the games. Then load it instantly.

**Comment by Raffa2005** [comment]
Unless I'm missing something, you cannot.
When I load my own pgn-file with games and analyze them I cannot save it
into a .tree file. Only appears to work for lichess/chesscom

Vanuj Juneja ***@***.***> schrieb am Mi., 23. Juni 2021,
16:40:
